"use client";

import { useEffect, useState } from "react";

type ReferData = {
  referralCode: string;
  referralLink: string;
  successfulReferrals: number;
  agentshipRequirement: number;
  agentshipUnlocked: boolean;
};

function CopyButton({ value }: { value: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      type="button"
      className="btn-secondary"
      style={{ height: 44, padding: "0 20px" }}
      onClick={async () => {
        try {
          await navigator.clipboard.writeText(value);
          setCopied(true);
          setTimeout(() => setCopied(false), 1500);
        } catch {
          /* clipboard unavailable — silently ignore */
        }
      }}
    >
      {copied ? "Copied" : "Copy"}
    </button>
  );
}

export function ReferView() {
  const [data, setData] = useState<ReferData | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch("/api/refer")
      .then((res) => {
        if (!res.ok) throw new Error(`API returned ${res.status}`);
        return res.json();
      })
      .then((d) => {
        if (!cancelled) setData(d);
      })
      .catch((err) => {
        if (!cancelled) setError(err instanceof Error ? err.message : "Failed to load referral stats");
      });
    return () => {
      cancelled = true;
    };
  }, []);

  if (error) return <div className="field-error" style={{ marginTop: 12 }}>{error}</div>;
  if (!data) return <div style={{ fontSize: 13, color: "var(--ash-500)", marginTop: 16 }}>Loading…</div>;

  const remaining = Math.max(0, data.agentshipRequirement - data.successfulReferrals);
  const progressPct = Math.min(100, Math.round((data.successfulReferrals / data.agentshipRequirement) * 100));

  return (
    <>
      <div style={{ background: "var(--moss-50)", border: "1px solid var(--moss-100)", borderRadius: "var(--r-lg)", padding: 14, marginTop: 12 }}>
        <div style={{ fontFamily: "var(--font-mono)", fontSize: 10.5, letterSpacing: ".12em", textTransform: "uppercase", color: "var(--moss-600)" }}>
          How partner earnings work
        </div>
        <div style={{ fontSize: 12.5, color: "var(--ink-700)", marginTop: 8, lineHeight: 1.6 }}>
          Referral Commission and Agentship Commission are calculated on the <strong>daily turnover of traders you refer</strong>. As your
          referred network processes volume, you earn the applicable percentage on that activity — subject to platform terms and eligibility.
        </div>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) minmax(0,1fr)", gap: 10, marginTop: 12 }}>
        <div style={{ background: "var(--paper)", border: "1px solid var(--border)", borderRadius: "var(--r-lg)", padding: 13 }}>
          <div style={{ fontFamily: "var(--font-mono)", fontSize: 10, letterSpacing: ".1em", textTransform: "uppercase", color: "var(--ash-500)" }}>
            Referral commission
          </div>
          <div style={{ fontFamily: "var(--font-mono)", fontSize: 22, fontWeight: 600, color: "var(--moss-600)", marginTop: 6 }}>0.3%</div>
          <div style={{ fontSize: 12, color: "var(--ash-600)", marginTop: 6 }}>Earn 0.3% of the daily turnover generated by traders you refer to FNGPAY.</div>
        </div>
        <div style={{ background: "var(--paper)", border: "1px solid var(--border)", borderRadius: "var(--r-lg)", padding: 13 }}>
          <div style={{ fontFamily: "var(--font-mono)", fontSize: 10, letterSpacing: ".1em", textTransform: "uppercase", color: "var(--ash-500)" }}>
            Agentship commission
          </div>
          <div style={{ fontFamily: "var(--font-mono)", fontSize: 22, fontWeight: 600, color: "var(--moss-600)", marginTop: 6 }}>1%</div>
          <div style={{ fontSize: 12, color: "var(--ash-600)", marginTop: 6 }}>
            As an approved Agentship partner, earn 1% of the daily turnover generated by traders under your referral network.
          </div>
        </div>
      </div>

      <div style={{ background: "var(--paper)", border: "1px solid var(--border)", borderRadius: "var(--r-lg)", padding: 14, marginTop: 12 }}>
        <div style={{ fontSize: 15.5, fontWeight: 600, color: "var(--ink-900)" }}>Your referral invite</div>
        <div style={{ fontSize: 12.5, color: "var(--ash-600)", marginTop: 3 }}>
          Share your code or link. When a trader registers with it, they count toward your referral network.
        </div>
        <div style={{ marginTop: 14 }}>
          <div style={{ fontFamily: "var(--font-mono)", fontSize: 10, letterSpacing: ".1em", textTransform: "uppercase", color: "var(--ash-500)" }}>Referral code</div>
          <div style={{ display: "flex", alignItems: "center", gap: 8, marginTop: 6 }}>
            <div
              style={{
                flex: 1,
                minWidth: 0,
                fontFamily: "var(--font-mono)",
                fontSize: 13,
                color: "var(--ink-800)",
                background: "var(--canvas)",
                border: "1px solid var(--border)",
                borderRadius: "var(--r-md)",
                padding: "9px 10px",
                overflow: "hidden",
                textOverflow: "ellipsis",
                whiteSpace: "nowrap",
              }}
            >
              {data.referralCode}
            </div>
            <CopyButton value={data.referralCode} />
          </div>
        </div>
        <div style={{ marginTop: 12 }}>
          <div style={{ fontFamily: "var(--font-mono)", fontSize: 10, letterSpacing: ".1em", textTransform: "uppercase", color: "var(--ash-500)" }}>Referral link</div>
          <div style={{ display: "flex", alignItems: "center", gap: 8, marginTop: 6 }}>
            <div
              style={{
                flex: 1,
                minWidth: 0,
                fontFamily: "var(--font-mono)",
                fontSize: 12,
                color: "var(--ink-800)",
                background: "var(--canvas)",
                border: "1px solid var(--border)",
                borderRadius: "var(--r-md)",
                padding: "9px 10px",
                overflow: "hidden",
                textOverflow: "ellipsis",
                whiteSpace: "nowrap",
              }}
            >
              {data.referralLink}
            </div>
            <CopyButton value={data.referralLink} />
          </div>
        </div>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) minmax(0,1fr)", gap: 10, marginTop: 12 }}>
        <div style={{ background: "var(--paper)", border: "1px solid var(--border)", borderRadius: "var(--r-lg)", padding: 13 }}>
          <div style={{ fontSize: 12, color: "var(--ash-600)" }}>Successful referrals</div>
          <div style={{ fontFamily: "var(--font-mono)", fontSize: 22, fontWeight: 600, color: "var(--ink-900)", marginTop: 6 }}>{data.successfulReferrals}</div>
        </div>
        <div style={{ background: "var(--paper)", border: "1px solid var(--border)", borderRadius: "var(--r-lg)", padding: 13 }}>
          <div style={{ fontSize: 12, color: "var(--ash-600)" }}>Agentship requirement</div>
          <div style={{ fontFamily: "var(--font-mono)", fontSize: 22, fontWeight: 600, color: "var(--ink-900)", marginTop: 6 }}>{data.agentshipRequirement}</div>
          <div style={{ fontSize: 11.5, color: "var(--ash-500)", marginTop: 2 }}>minimum referrals</div>
        </div>
      </div>

      <div style={{ background: "var(--paper)", border: "1px solid var(--border)", borderRadius: "var(--r-lg)", padding: 14, marginTop: 12 }}>
        <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 10 }}>
          <div style={{ fontSize: 15.5, fontWeight: 600, color: "var(--ink-900)" }}>Apply for Agentship</div>
          <span className={`badge ${data.agentshipUnlocked ? "badge-green" : "badge-amber"}`}>{data.agentshipUnlocked ? "Unlocked" : "Locked"}</span>
        </div>
        <div style={{ fontSize: 12.5, color: "var(--ash-600)", marginTop: 6, lineHeight: 1.6 }}>
          Unlock Agentship to earn <strong>1%</strong> on the daily turnover of traders in your referral network. Application opens after you
          complete <strong>{data.agentshipRequirement} successful referrals</strong>.
        </div>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10, marginTop: 12 }}>
          <div style={{ fontSize: 12, color: "var(--ash-600)" }}>
            Progress: {data.successfulReferrals} / {data.agentshipRequirement}
          </div>
          <div style={{ fontSize: 12, color: "var(--ash-500)" }}>{remaining === 0 ? "Requirement met" : `${remaining} more referrals needed`}</div>
        </div>
        <div style={{ height: 6, borderRadius: "var(--r-pill)", background: "var(--ash-200)", marginTop: 8, overflow: "hidden" }}>
          <div style={{ width: `${progressPct}%`, height: "100%", background: "var(--moss-500)" }} />
        </div>
        <div style={{ marginTop: 12 }}>
          <button
            type="button"
            className="btn-secondary"
            disabled={!data.agentshipUnlocked}
            style={{ width: "100%", height: 44, fontSize: 14, opacity: data.agentshipUnlocked ? 1 : 0.5, cursor: data.agentshipUnlocked ? "pointer" : "not-allowed" }}
          >
            Apply for Agentship
          </button>
        </div>
        <div style={{ fontSize: 12, color: "var(--ash-500)", marginTop: 10 }}>
          The Apply for Agentship button stays locked until you have at least {data.agentshipRequirement} successful referrals.
        </div>
      </div>
    </>
  );
}
